apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-devops
  labels:
    app: service-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-devops
  template:
    metadata:
      labels:
        app: service-devops
    spec:
      containers:
      - name: service-devops
        image: antony0618/simple-devops
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-devops
spec:
  type: LoadBalancer
  selector:
    app: service-devops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080